# Generated by Django 2.1.2 on 2018-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181101_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/SET_DEFAULT/', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='/SET_DEFAULT/', upload_to='themes/'),
        ),
    ]
